In [40]:
import pandas as pd
import numpy as np

In [41]:
v1 = pd.read_csv('clear_data/df_prices_v1.csv')
v1.head(50)

,price,game,mini,faction
0,70.84,NaN,Custodian Dreadnought,Adeptus_Custodes
1,67.62,NaN,Sentinel Guard Sodality,Adeptus_Custodes
2,40.02,NaN,Shield Captain,Adeptus_Custodes
3,75.44,NaN,Venatari Sodality,Adeptus_Custodes
4,67.62,NaN,Custodian Guard Sodality,Adeptus_Custodes
5,92.00,NaN,Caladius Annihilator Grav-tank,Adeptus_Custodes
6,92.00,NaN,Caladius Grav-tank,Adeptus_Custodes
7,116.84,NaN,Coronus Grav-carrier,Adeptus_Custodes
8,55.20,NaN,Hastarii,Adeptus_Mechanicus
9,59.80,NaN,Thulia Ghuld,Adeptus_Mechanicus
10,63.48,NaN,Mutilators,Chaos_Space_Marines
11,32.20,NaN,Iron Warriors Upgrades,NaN
12,156.40,NaN,Knight Destrier,Imperial_Knights
13,156.40,Eye of Terror Battalion,NaN,Adeptus_Mechanicus
14,193.20,Eye of Terror Battalion,NaN,Imperial_Knights
15,40.02,NaN,Tyranid Prime with Lash Whip,Tyranids
16,59.80,NaN,Vyper/Starfang,Craftworlds
17,59.80,NaN,Corsair Voidreavers,NaN
18,55.20,NaN,Corsair Skyreavers,NaN
19,40.02,NaN,Kharseth,NaN
20,43.24,NaN,Prince Yriel,NaN
21,32.20,NaN,Red Corsairs Upgrades and Transfers,NaN
22,59.80,NaN,Red Corsairs Raiders,NaN
23,156.40,Combat Patrol,NaN,Drukhari
24,156.40,Combat Patrol,Leagues of Votann,NaN
25,156.40,Combat Patrol,Tyranid Assault Brood,Tyranids
26,156.40,Combat Patrol,Black Templars,Supplement_Marines
27,156.40,Combat Patrol,NaN,Grey_Knights
28,156.40,Combat Patrol,NaN,Thousand_Sons
29,156.40,Combat Patrol,Emperor's Children,NaN
30,156.40,Combat Patrol,World Eaters,NaN
31,156.40,Combat Patrol,Aeldari,Craftworlds
32,156.40,Combat Patrol,NaN,Astra_Militarum
33,156.40,Combat Patrol,NaN,Blood_Angels
34,156.40,Combat Patrol,Imperial Agents,NaN
35,156.40,Combat Patrol,s,Genestealer_Cult
36,156.40,Combat Patrol,NaN,Adepta_Sororitas
37,156.40,Combat Patrol,T’au Empire,NaN
38,156.40,Combat Patrol,NaN,Adeptus_Custodes
39,156.40,Combat Patrol,NaN,Orks
40,156.40,Combat Patrol,NaN,Dark_Angels
41,156.40,Combat Patrol,NaN,Adeptus_Mechanicus
42,156.40,Combat Patrol,NaN,Necrons
43,44.16,NaN,Wyches,NaN
44,63.48,NaN,Manticore,NaN
45,29.44,NaN,Support Weapon,NaN
46,73.60,NaN,Baal Predator,Space_Marines
47,63.48,NaN,Basilisk,Astra_Militarum
48,59.80,NaN,Chimera,Astra_Militarum
49,59.80,NaN,Killa Kans,NaN

In [42]:
v2 = pd.read_csv('clear_data/df_prices_v2.csv')
v2.head(50)

     price                                 mini              faction
0    56.12                      Custodian Guard     Adeptus_Custodes
1    46.00                   Sisters Of Silence     Adeptus_Custodes
2    35.88      Captain General Trajann Valoris     Adeptus_Custodes
3    56.12                    Custodian Wardens     Adeptus_Custodes
4    56.12                      Vertus Praetors     Adeptus_Custodes
5    46.92                   Allarus Custodians     Adeptus_Custodes
6    10.12                   Etb Chaos Cultists  Chaos_Space_Marines
7    35.88                             Veterans           Deathwatch
8    74.52                     Corvus Blackstar           Deathwatch
9    32.20                         Watch Master           Deathwatch
10   13.80                             Upgrades           Deathwatch
11  129.72                        Combat Patrol           Deathwatch
12   35.88                        Death Company         Blood_Angels
13   45.08                     Sanguinary Guard         Blood_Angels
14   98.44                   Stormraven Gunship        Space_Marines
15   55.20                  Furioso Dreadnought         Blood_Angels
16   31.28                    Sanguinary Priest         Blood_Angels
17   33.12              Chaplain With Jump Pack         Blood_Angels
18   42.32           Death Company Intercessors         Blood_Angels
19  129.72                        Combat Patrol         Blood_Angels
20   13.80                    Primaris Upgrades         Blood_Angels
21   37.72                            Mephiston         Blood_Angels
22   14.72                             Upgrades         Blood_Angels
23   37.72                               Bikers  Chaos_Space_Marines
24   45.08                    Khorne Berzerkers        Chaos_Daemons
25   41.40                                Rhino  Chaos_Space_Marines
26   28.52                           Chaos Lord  Chaos_Space_Marines
27   35.88                              Raptors  Chaos_Space_Marines
28   69.92                           Forgefiend  Chaos_Space_Marines
29   69.00                             Heldrake  Chaos_Space_Marines
30   56.12                          Terminators  Chaos_Space_Marines
31   34.04       Chaos S/M Haarken Worldclaimer        Chaos_Daemons
32   28.52                   Biologus Putrifier          Death_Guard
33   33.12                   Kharn The Betrayer        Chaos_Daemons
34   35.88                            Possessed  Chaos_Space_Marines
35   28.52                     Nauseous Rotbone          Death_Guard
36  139.84                       Magnus The Red        Thousand_Sons
37   55.20                       Rubric Marines        Thousand_Sons
38   56.12            Scarab Occult Terminators        Thousand_Sons
39   33.12                         Dark Apostle  Chaos_Space_Marines
40   37.72    Ahriman Arch Sorcerer Of Tzeentch        Chaos_Daemons
41   56.12                    Exalted Sorcerers        Thousand_Sons
42   28.52                 Master Of Executions  Chaos_Space_Marines
43   28.52              D/G Scribbus Wretch The        Chaos_Daemons
44   28.52                     Foul Blightspawn          Death_Guard
45   28.52            Plague Marine Icon Bearer          Death_Guard
46   28.52               Plague Marine Champion          Death_Guard
47  139.84  Mortarion Daemon Primarch Of Nurgle        Chaos_Daemons
48   56.12                Deathshroud Bodyguard          Death_Guard
49   56.12               Blightlord Terminators          Death_Guard

In [43]:
mat = pd.read_csv('clear_data/df_materials.csv')
mat

,mini,faction,material,edition,year
0,Baharroth Wings,Craftworlds,Metal,Warhammer 40K: Rogue Trader,1990.0
1,Warp Spiders,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
2,Avatar of Khaine,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
3,Asurmen,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
4,Karandras,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
...,...,...,...,...,...
977,Ahriman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2016.0
978,Tzaangor Enlightened,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
979,Tzaangor Skyfires,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
980,Tzaangor Shaman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
981,Infernal Master,Thousand_Sons,Plastic,Warhammer 40K: 9th Edition,2021.0

In [44]:
v3_concat = pd.concat([v1, v2], ignore_index=True)

# Filtrar los 'mini' que aparecen más de una vez (coincidencias)
coincidencias = v3_concat['mini'].value_counts()
mini_coincidentes = coincidencias[coincidencias > 1].index

# Filtrar el DataFrame solo con las coincidencias
v3_filtrado = v3_concat[v3_concat['mini'].isin(mini_coincidentes)]
v3_filtrado = v3_filtrado.sort_values(by='mini').reset_index(drop=True)
v3_filtrado

     price            game                     mini             faction
0    32.20  Black Templars   Upgrades and Transfers  Supplement_Marines
1    32.20     Dark Angels   Upgrades and Transfers  Supplement_Marines
2    37.72             NaN            Adrax Agatone  Supplement_Marines
3    43.24             NaN            Adrax Agatone                 NaN
4    55.20             NaN       Allarus Custodians    Adeptus_Custodes
..     ...             ...                      ...                 ...
322  59.80             NaN               Wraithlord         Craftworlds
323  59.80             NaN                   Wulfen        Space_Wolves
324  56.12             NaN                   Wulfen        Space_Wolves
325  34.04             NaN                   Wyches            Drukhari
326  44.16             NaN                   Wyches                 NaN

[327 rows x 4 columns]