In [1]:
import pandas as pd
import numpy as np

In [2]:
def hojas_a_df(ruta_archivo):
    """Lee el Excel y crea variables globales con prefijo df_"""
    from IPython import get_ipython
    dfs = pd.read_excel(ruta_archivo, sheet_name=None)
    shell = get_ipython()
    for nombre, df in dfs.items():
        nombre_var = 'df_' + nombre.replace(' ', '_').replace('-', '_')
        shell.user_ns[nombre_var] = df
    return dfs

hojas_a_df('data/materiales.xlsx')

{'Table of Contents':     Unnamed: 0         Table of Contents               Unnamed: 2
 0          NaN              40K Editions                      NaN
 1          NaN            Codex Releases                      NaN
 2          NaN               Craftworlds                      NaN
 3          NaN                  Drukhari                      NaN
 4          NaN                Harlequins                      NaN
 5          NaN                    Ynnari                      NaN
 6          NaN          Genestealer Cult                      NaN
 7          NaN                  Tyranids                      NaN
 8          NaN                   Necrons                      NaN
 9          NaN                      Orks                      NaN
 10         NaN                Tau Empire                      NaN
 11         NaN             Space Marines                      NaN
 12         NaN        Supplement Marines                      NaN
 13         NaN              Blood Angels                      NaN
 14         NaN               Dark Angels                      NaN
 15         NaN              Space Wolves                      NaN
 16         NaN                Deathwatch                      NaN
 17         NaN              Grey Knights                      NaN
 18         NaN           Astra Militarum                      NaN
 19         NaN          Adepta Sororitas                      NaN
 20         NaN          Adeptus Custodes                      NaN
 21         NaN        Adeptus Mechanicus                      NaN
 22         NaN        Imperial Assassins                      NaN
 23         NaN          Imperial Knights                      NaN
 24         NaN               Inquisition                      NaN
 25         NaN             Chaos Daemons                      NaN
 26         NaN             Chaos Knights                      NaN
 27         NaN       Chaos Space Marines                      NaN
 28         NaN               Death Guard                      NaN
 29         NaN             Thousand Sons                      NaN
 30         NaN                       NaN                      NaN
 31         NaN                       NaN                      NaN
 32         NaN                       NaN                      NaN
 33         NaN                       NaN                      NaN
 34         NaN                       NaN                      NaN
 35         NaN  Last added new releases:      2022-05-04 00:00:00
 36         NaN                       NaN                      NaN
 37         NaN        Feedback & errors:  https://redd.it/10xuc9j,
 'Data - All Factions':      Year                                      Craftworlds Drukhari  \
 0    1990  Baharroth Wings (RT Swooping Hawk Exarch Wings)      NaN
 1    1991                                              NaN      NaN
 2    1992                                              NaN      NaN
 3    1993                                              NaN      NaN
 4    1993                                              NaN      NaN
 ..    ...                                              ...      ...
 250  2020                                              NaN      NaN
 251  2020                                              NaN      NaN
 252  2020                                              NaN      NaN
 253  2020                                              NaN      NaN
 254  2020                                              NaN      NaN

     Harlequins Ynnari             Space Marines Blood Angels Black Templars  \
 0          NaN    NaN                       NaN          NaN            NaN
 1          NaN    NaN                       NaN          NaN            NaN
 2          NaN    NaN                       NaN          NaN            NaN
 3          NaN    NaN  Servitors with Servo-Arm          NaN            NaN
 4          NaN    NaN                       NaN          NaN            NaN
 ..         ...    ...                       ...          ...            ...
 250        NaN    NaN                       NaN          NaN            NaN
 251        NaN    NaN                       NaN          NaN            NaN
 252        NaN    NaN                       NaN          NaN            NaN
 253        NaN    NaN                       NaN          NaN            NaN
 254        NaN    NaN                       NaN          NaN            NaN

     Crimson Fists Dark Angels  ... Imperial Assassins Chaos Space Marines  \
 0             NaN         NaN  ...                NaN                 NaN
 1             NaN         NaN  ...                NaN                 NaN
 2             NaN         NaN  ...                NaN                 NaN
 3             NaN         NaN  ...                NaN                 NaN
 4             NaN         NaN  ...                NaN                 NaN
 ..            ...         ...  ...                ...                 ...
 250           NaN         NaN  ...                NaN                 NaN
 251           NaN         NaN  ...                NaN                 NaN
 252           NaN         NaN  ...                NaN                 NaN
 253           NaN         NaN  ...                NaN                 NaN
 254           NaN         NaN  ...                NaN                 NaN

     Death Guard Thousand Sons Chaos Daemons Genestealer Cult Necrons Orks  \
 0           NaN           NaN           NaN              NaN     NaN  NaN
 1           NaN           NaN           NaN              NaN     NaN  NaN
 2           NaN           NaN           NaN              NaN     NaN  NaN
 3           NaN           NaN           NaN              NaN     NaN  NaN
 4           NaN           NaN           NaN              NaN     NaN  NaN
 ..          ...           ...           ...              ...     ...  ...
 250         NaN           NaN           NaN              NaN     NaN  NaN
 251         NaN           NaN           NaN              NaN     NaN  NaN
 252         NaN           NaN           NaN              NaN     NaN  NaN
 253         NaN           NaN           NaN              NaN     NaN  NaN
 254         NaN           NaN           NaN              NaN     NaN  NaN

     Tau Empire Tyranids
 0          NaN      NaN
 1          NaN      NaN
 2          NaN      NaN
 3          NaN      NaN
 4          NaN      NaN
 ..         ...      ...
 250        NaN      NaN
 251        NaN      NaN
 252        NaN      NaN
 253        NaN      NaN
 254        NaN      NaN

 [255 rows x 35 columns],
 'Data - All Factions - Coloured ':      Year                                      Craftworlds Drukhari  \
 0    1990  Baharroth Wings (RT Swooping Hawk Exarch Wings)      NaN
 1    1991                                              NaN      NaN
 2    1992                                              NaN      NaN
 3    1993                                              NaN      NaN
 4    1993                                              NaN      NaN
 ..    ...                                              ...      ...
 250  2020                                              NaN      NaN
 251  2020                                              NaN      NaN
 252  2020                                              NaN      NaN
 253  2020                                              NaN      NaN
 254  2020                                              NaN      NaN

     Harlequins Ynnari             Space Marines Blood Angels Black Templars  \
 0          NaN    NaN                       NaN          NaN            NaN
 1          NaN    NaN                       NaN          NaN            NaN
 2          NaN    NaN                       NaN          NaN            NaN
 3          NaN    NaN  Servitors with Servo-Arm          NaN            NaN
 4          NaN    NaN                       NaN          NaN            NaN
 ..         ...    ...                       ...          ...            ...
 250        NaN    NaN                       NaN          NaN            NaN
 251        NaN    NaN                       NaN          NaN            NaN
 252        NaN    NaN                       NaN          NaN            NaN
 253        NaN    NaN                       NaN          NaN            NaN
 254        NaN    NaN                       NaN          NaN            NaN

     Crimson Fists Dark Angels  ... Imperial Assassins Chaos Space Marines  \
 0             NaN         NaN  ...                NaN                 NaN
 1             NaN         NaN  ...                NaN                 NaN
 2             NaN         NaN  ...                NaN                 NaN
 3             NaN         NaN  ...                NaN                 NaN
 4             NaN         NaN  ...                NaN                 NaN
 ..            ...         ...  ...                ...                 ...
 250           NaN         NaN  ...                NaN                 NaN
 251           NaN         NaN  ...                NaN                 NaN
 252           NaN         NaN  ...                NaN                 NaN
 253           NaN         NaN  ...                NaN                 NaN
 254           NaN         NaN  ...                NaN                 NaN

     Death Guard Thousand Sons Chaos Daemons Genestealer Cult Necrons Orks  \
 0           NaN           NaN           NaN              NaN     NaN  NaN
 1           NaN           NaN           NaN              NaN     NaN  NaN
 2           NaN           NaN           NaN              NaN     NaN  NaN
 3           NaN           NaN           NaN              NaN     NaN  NaN
 4           NaN           NaN           NaN              NaN     NaN  NaN
 ..          ...           ...           ...              ...     ...  ...
 250         NaN           NaN           NaN              NaN     NaN  NaN
 251         NaN           NaN           NaN              NaN     NaN  NaN
 252         NaN           NaN           NaN              NaN     NaN  NaN
 253         NaN           NaN           NaN              NaN     NaN  NaN
 254         NaN           NaN           NaN              NaN     NaN  NaN

     Tau Empire Tyranids
 0          NaN      NaN
 1          NaN      NaN
 2          NaN      NaN
 3          NaN      NaN
 4          NaN      NaN
 ..         ...      ...
 250        NaN      NaN
 251        NaN      NaN
 252        NaN      NaN
 253        NaN      NaN
 254        NaN      NaN

 [255 rows x 35 columns],
 '40K Editions':   Year-Month                      Release
 0 1987-09-01  Warhammer 40K: Rogue Trader
 1 1993-10-01   Warhammer 40K: 2nd Edition
 2 1998-10-01   Warhammer 40K: 3rd Edition
 3 2004-08-01   Warhammer 40K: 4th Edition
 4 2008-07-01   Warhammer 40K: 5th Edition
 5 2012-06-01   Warhammer 40K: 6th Edition
 6 2014-05-01   Warhammer 40K: 7th Edition
 7 2017-06-01   Warhammer 40K: 8th Edition
 8 2020-07-01   Warhammer 40K: 9th Edition
 9 2023-06-01  Warhammer 40K: 10th Edition,
 'Codex Releases':    Year-Month                     Release Note
 0  2017-06-01  Warhammer 40K: 8th Edition  NaN
 1  2017-07-01        Codex: Space Marines  NaN
 2  2017-08-01  Codex: Chaos Space Marines  NaN
 3  2017-08-01         Codex: Grey Knights  NaN
 4  2017-09-01          Codex: Death Guard  NaN
 ..        ...                         ...  ...
 66 2024-04-01     Codex: Adeptus Custodes  NaN
 67 2024-05-01  Codex: Chaos Space Marines  NaN
 68 2024-06-01     Codex: Adepta Sororitas  NaN
 69 2024-06-01    Codex: Genestealer Cults  NaN
 70 2024-08-01      Codex: Imperial Agents  NaN

 [71 rows x 3 columns],
 'Craftworlds':    Year-Month                      Release  \
 0  1987-09-01  Warhammer 40K: Rogue Trader
 1  1990-11-01              Baharroth Wings
 2         NaT                          NaN
 3  1993-10-01   Warhammer 40K: 2nd Edition
 4  1994-03-01                 Warp Spiders
 ..        ...                          ...
 74 2022-03-01                     Warlocks
 75 2022-03-01                    Guardians
 76 2022-03-01              Storm Guardians
 77 2022-03-01             Avatar of Khaine
 78 2022-03-01               Shining Spears

                                        Note Current Material Unnamed: 4
 0                                       NaN              NaN        NaN
 1   From Rogue Trader Swooping Hawks Exarch            Metal        NaN
 2                                       NaN              NaN        NaN
 3                                       NaN              NaN        NaN
 4                                       NaN         Finecast        NaN
 ..                                      ...              ...        ...
 74                                      NaN          Plastic        NaN
 75                         Shared Multi-kit          Plastic        NaN
 76                                      NaN              NaN        NaN
 77                                      NaN          Plastic        NaN
 78                                      NaN          Plastic        NaN

 [79 rows x 5 columns],
 'Drukhari':    Year-Month                      Release  \
 0  1987-09-01  Warhammer 40K: Rogue Trader
 1         NaT                          NaN
 2         NaT                          NaN
 3  1993-10-01   Warhammer 40K: 2nd Edition
 4         NaT                          NaN
 5         NaT                          NaN
 6  1998-10-01   Warhammer 40K: 3rd Edition
 7         NaT                          NaN
 8         NaT                          NaN
 9  2004-08-01   Warhammer 40K: 4th Edition
 10        NaT                          NaN
 11        NaT                          NaN
 12 2008-07-01   Warhammer 40K: 5th Edition
 13 2010-11-01            Kabalite Warriors
 14 2010-11-01                       Wyches
 15 2010-11-01                      Reavers
 16 2010-11-01                     Hellions
 17 2010-11-01                       Raider
 18 2010-11-01                      Ravager
 19 2010-11-01                    Mandrakes
 20 2010-11-01                Urien Rakarth
 21 2010-11-01              Lelith Hesperax
 22 2011-03-01                  Beastmaster
 23 2011-03-01                     Khymerae
 24 2011-03-01                 Clawed Fiend
 25 2011-03-01              Razorwing Flock
 26 2011-06-01                     Scourges
 27 2011-06-01                        Talos
 28 2011-06-01                       Cronos
 29 2011-06-01         Razorwing Jetfighter
 30 2011-06-01                        Venom
 31 2011-06-01                    Grotesque
 32 2011-08-01                      Ur-Ghul
 33 2011-08-01                      Medusae
 34 2011-09-01                       Sslyth
 35 2011-09-01                     Lhamaean
 36        NaT                          NaN
 37 2012-06-01   Warhammer 40K: 6th Edition
 38 2014-09-01                  Haemonculus
 39 2014-09-01                       Wracks
 40 2014-09-01             Voidraven Bomber
 41 2014-10-01                     Succubus
 42 2014-10-01                       Archon
 43        NaT                          NaN
 44 2014-05-01   Warhammer 40K: 7th Edition
 45        NaT                          NaN
 46        NaT                          NaN
 47 2017-06-01   Warhammer 40K: 8th Edition
 48 2019-10-01                      Drazhar
 49 2019-10-01                       Incubi
 50        NaT                          NaN
 51 2020-07-01   Warhammer 40K: 9th Edition
 52 2021-03-01              Lelith Hesperax

                                                Note Current Material
 0                                               NaN              NaN
 1                                               NaN              NaN
 2                                               NaN              NaN
 3                                               NaN              NaN
 4                                               NaN              NaN
 5                                               NaN              NaN
 6                                               NaN              NaN
 7                                               NaN              NaN
 8                                               NaN              NaN
 9                                               NaN              NaN
 10                                              NaN              NaN
 11                                              NaN              NaN
 12                                              NaN              NaN
 13                                              NaN          Plastic
 14                                              NaN          Plastic
 15                                              NaN          Plastic
 16                                              NaN          Plastic
 17                                              NaN          Plastic
 18                      Raider kit with extra sprue          Plastic
 19                                              NaN         Finecast
 20                                              NaN         Finecast
 21                                              NaN         Finecast
 22                                              NaN         Finecast
 23                                              NaN         Finecast
 24                                              NaN         Finecast
 25                                              NaN         Finecast
 26                                              NaN          Plastic
 27                                 Shared Multi-kit          Plastic
 28                                              NaN              NaN
 29                                              NaN          Plastic
 30                                              NaN          Plastic
 31                                              NaN         Finecast
 32                                              NaN         Finecast
 33                                              NaN         Finecast
 34                                              NaN         Finecast
 35                                              NaN         Finecast
 36                                              NaN              NaN
 37                                              NaN              NaN
 38                                              NaN          Plastic
 39                                              NaN          Plastic
 40                                              NaN          Plastic
 41                                              NaN          Plastic
 42                                              NaN          Plastic
 43                                              NaN              NaN
 44                                              NaN              NaN
 45                                              NaN              NaN
 46                                              NaN              NaN
 47                                              NaN              NaN
 48  Blood of the Phoenix box – Solo release 2020-03          Plastic
 49  Blood of the Phoenix box – Solo release 2020-03          Plastic
 50                                              NaN              NaN
 51                                              NaN              NaN
 52        Piety and Pain box - Solo release 2021-05          Plastic  ,
 'Harlequins':    Year-Month                      Release              Note Current Material
 0  1987-09-01  Warhammer 40K: Rogue Trader               NaN              NaN
 1         NaT                          NaN               NaN              NaN
 2         NaT                          NaN               NaN              NaN
 3  1993-10-01   Warhammer 40K: 2nd Edition               NaN              NaN
 4         NaT                          NaN               NaN              NaN
 5         NaT                          NaN               NaN              NaN
 6  1998-10-01   Warhammer 40K: 3rd Edition               NaN              NaN
 7         NaT                          NaN               NaN              NaN

In [3]:
df_materiales = pd.DataFrame(columns=('mini', 'faction', 'material', 'edition', 'year'))
df_materiales

Empty DataFrame
Columns: [mini, faction, material, edition, year]
Index: []

In [4]:
edition = df_40K_Editions.drop(columns=df_40K_Editions.columns[0])
edition = edition['Release'].tolist()
edition

['Warhammer 40K: Rogue Trader',
 'Warhammer 40K: 2nd Edition',
 'Warhammer 40K: 3rd Edition',
 'Warhammer 40K: 4th Edition',
 'Warhammer 40K: 5th Edition',
 'Warhammer 40K: 6th Edition',
 'Warhammer 40K: 7th Edition',
 'Warhammer 40K: 8th Edition',
 'Warhammer 40K: 9th Edition',
 'Warhammer 40K: 10th Edition']

In [5]:
faction = df_Table_of_Contents.drop(columns=df_Table_of_Contents.columns[[0, 2]])[2:30]
faction = faction['Table of Contents'].str.replace(' ', '_').tolist()
faction

['Craftworlds',
 'Drukhari',
 'Harlequins',
 'Ynnari',
 'Genestealer_Cult',
 'Tyranids',
 'Necrons',
 'Orks',
 'Tau_Empire',
 'Space_Marines',
 'Supplement_Marines',
 'Blood_Angels',
 'Dark_Angels',
 'Space_Wolves',
 'Deathwatch',
 'Grey_Knights',
 'Astra_Militarum',
 'Adepta_Sororitas',
 'Adeptus_Custodes',
 'Adeptus_Mechanicus',
 'Imperial_Assassins',
 'Imperial_Knights',
 'Inquisition',
 'Chaos_Daemons',
 'Chaos_Knights',
 'Chaos_Space_Marines',
 'Death_Guard',
 'Thousand_Sons']

In [6]:
def dateFormater(df, dateColumn):
    df[dateColumn] = pd.to_datetime(df[dateColumn])
    df['year'] = df[dateColumn].dt.year.astype('Int64')
    df.drop(dateColumn, axis=1, inplace=True)
    if 'day' in df.columns:
        df.drop('day', axis=1, inplace=True)
    if 'month' in df.columns:
        df.drop('month', axis=1, inplace=True)

In [7]:
def process_faction(df, faction_name):
    if 'Year-Month' in df.columns:
        dateFormater(df, 'Year-Month')
    
    df = df.rename(columns={'Release': 'mini', 'Current Material': 'material'})
    df = df.drop(columns=[c for c in ['Unnamed: 4'] if c in df.columns])

    df = df.dropna(subset=['mini'])

    mask = df['mini'].isin(edition)
    df['edition'] = df['mini'].where(mask).ffill()
    df = df[~df['mini'].str.contains('Warhammer')]
    df = df.replace(False, np.nan).dropna(how='all')

    df = df.reset_index(drop=True)
    df['material'] = df['material'].fillna('Plastic')

    df['faction'] = faction_name.replace('df_', '')
    df = df[df_materiales.columns]

    return df

In [8]:
def creator(factionList, all_dfs):
    df_list = []
    
    for f in factionList:
        df = all_dfs[f'df_{f}']
        processed_df = process_faction(df, f)
        df_list.append(processed_df)
    
    return pd.concat(df_list, ignore_index=True)

df_combined = creator(faction, globals())

In [ ]:
df_combined.to_csv('clear_data/df_materials.csv', index=False)
df_combined

,mini,faction,material,edition,year
0,Baharroth Wings,Craftworlds,Metal,Warhammer 40K: Rogue Trader,1990
1,Warp Spiders,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994
2,Avatar of Khaine,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994
3,Asurmen,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994
4,Karandras,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994
...,...,...,...,...,...
977,Ahriman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2016
978,Tzaangor Enlightened,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017
979,Tzaangor Skyfires,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017
980,Tzaangor Shaman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017
981,Infernal Master,Thousand_Sons,Plastic,Warhammer 40K: 9th Edition,2021